name: Generate and Publish Notebook Release

on:
  push:
    branches: [main]

permissions:
  contents: write  # Allow GitHub Actions to create releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1'

    - uses: julia-actions/cache@v2

    - name: Modify global env
      shell: julia --color=yes {0}
      run: |
         using Pkg;
         Pkg.add(["Literate", "NBInclude"])
         Pkg.instantiate()

    - name: Generate Notebook
      run: julia gen_notebook.jl

    - name: Create Notebook Archive
      run: zip -r notebook.zip notebook/


    - name: Test the notebook
      shell: julia --project=notebook --color=yes {0}
      run: |
         import Pkg;
         Pkg.instantiate()
         using NBInclude
         @nbinclude("workshop.ipynb")

    - name: Get Commit SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: notebook-${{ env.sha_short }}  # Unique tag per commit
        name: "Notebook Release (${{ env.sha_short }})"
        files: notebook.zip
        body: "Automated notebook release for commit [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
