name: Generate and Publish Notebook Release

on:
  push:
    branches: [main]

permissions:
  contents: write  # Allow GitHub Actions to create releases

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: '1'

    - uses: julia-actions/cache@v2

    - name: Generate Notebook
      run: julia gen_notebook.jl

    - name: Create Notebook Archive
      run: zip -r notebook.zip notebook/

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: latest
        name: "Notebook Release (${{ github.sha }})"
        files: notebook.zip
        body: "Automated notebook release for commit [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
